<?php
/**
 * ADMIN TEST: Pagar.me Split Payment Feature
 * Test 3-way real-time payment splits
 */
$script = 'pagarme';
require_once('../../common.php');
if (!isset($_SESSION['admin_id'])) { header("Location: ../../login.php"); exit; }

$result  = null;
$defined = defined('PAGARME_SECRET_KEY') && PAGARME_SECRET_KEY !== 'sk_YOUR_KEY';

require_once dirname(__DIR__, 2) . '/features/PagarmePayment.php';
$pagarme = new PagarmePayment($obj, $tconfig);

if ($_SERVER['REQUEST_METHOD'] === 'POST' && SITE_TYPE !== 'Demo') {
    $result = json_decode($pagarme->handleRequest($_POST), true);
}

include('../../header.php');
?>
<div class="content-wrapper">
  <section class="content-header">
    <h1>💳 Pagar.me Split Payment <small>3-way real-time payment split test</small></h1>
    <ol class="breadcrumb">
      <li><a href="../admin.php"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="../dashboard.php">Dashboard</a></li>
      <li class="active">Pagar.me Split Pay</li>
    </ol>
  </section>
  <section class="content">

    <?php if (!$defined): ?>
    <div class="alert alert-warning">
      <strong>Setup Required:</strong> Add your Pagar.me API keys to <code>app_configuration_file.php</code>:
      <br><code>define('PAGARME_SECRET_KEY', 'sk_...');</code>
      <br><code>define('PAGARME_PUBLIC_KEY', 'pk_...');</code>
      <br><code>define('PAGARME_MASTER_RECIPIENT_ID', 'rp_...');</code>
    </div>
    <?php endif; ?>

    <?php if ($result): ?>
    <div class="alert alert-<?= ($result['status'] ?? '') === 'success' ? 'success' : 'danger' ?> alert-dismissible">
      <button class="close" data-dismiss="alert">&times;</button>
      <?= htmlspecialchars($result['message'] ?? json_encode($result)) ?>
    </div>
    <?php endif; ?>

    <div class="row">
      <div class="col-md-5">

        <!-- Process Ride Payment -->
        <div class="box box-primary">
          <div class="box-header with-border"><h3 class="box-title"><i class="fa fa-credit-card"></i> Process Ride Payment</h3></div>
          <form method="POST">
            <input type="hidden" name="pagarme_action" value="processRidePayment">
            <div class="box-body">
              <div class="form-group">
                <label>Request ID</label>
                <input type="number" name="iRequestId" class="form-control" value="100">
              </div>
              <div class="form-group">
                <label>Trip ID</label>
                <input type="number" name="iTripId" class="form-control" value="50">
              </div>
              <div class="form-group">
                <label>Driver ID</label>
                <input type="number" name="iDriverId" class="form-control" value="1">
              </div>
              <div class="form-group">
                <label>User ID (Passenger)</label>
                <input type="number" name="iUserId" class="form-control" value="1">
              </div>
              <div class="form-group">
                <label>Franchise ID (0 = no franchise)</label>
                <input type="number" name="iFranchiseId" class="form-control" value="0">
              </div>
              <div class="form-group">
                <label>Total Amount (R$)</label>
                <input type="number" name="fTotalAmount" class="form-control" step="0.01" value="35.50">
              </div>
              <div class="form-group">
                <label>Payment Token (from Pagar.me.js)</label>
                <input type="text" name="vPaymentToken" class="form-control" placeholder="tok_...">
                <small class="help-block">Token generated by Pagar.me.js on the client side.</small>
              </div>
            </div>
            <div class="box-footer">
              <button type="submit" class="btn btn-primary <?= !$defined ? 'disabled' : '' ?>">
                <i class="fa fa-send"></i> Process Payment
              </button>
            </div>
          </form>
        </div>

        <!-- Create Recipient -->
        <div class="box box-default">
          <div class="box-header with-border"><h3 class="box-title"><i class="fa fa-user-plus"></i> Create Driver Recipient</h3></div>
          <form method="POST">
            <input type="hidden" name="pagarme_action" value="createRecipient">
            <div class="box-body">
              <div class="form-group">
                <label>Driver ID</label>
                <input type="number" name="iDriverId" class="form-control" value="1">
              </div>
              <div class="form-group">
                <label>Bank Code (e.g. 341 = Itaú)</label>
                <input type="text" name="vBankCode" class="form-control" value="341">
              </div>
              <div class="form-group">
                <label>Agency</label>
                <input type="text" name="vAgency" class="form-control" value="0001">
              </div>
              <div class="form-group">
                <label>Account Number</label>
                <input type="text" name="vAccount" class="form-control" value="12345-6">
              </div>
              <div class="form-group">
                <label>Account Type</label>
                <select name="vAccountType" class="form-control">
                  <option value="conta_corrente">Conta Corrente</option>
                  <option value="conta_poupanca">Conta Poupança</option>
                </select>
              </div>
              <div class="form-group">
                <label>CPF / CNPJ</label>
                <input type="text" name="vDocument" class="form-control" placeholder="123.456.789-00">
              </div>
            </div>
            <div class="box-footer">
              <button type="submit" class="btn btn-default <?= !$defined ? 'disabled' : '' ?>">
                <i class="fa fa-plus"></i> Create Recipient
              </button>
            </div>
          </form>
        </div>

      </div>

      <div class="col-md-7">
        <div class="box box-info">
          <div class="box-header with-border"><h3 class="box-title">How Split Payment Works</h3></div>
          <div class="box-body">
            <p>When a ride is completed, Pagar.me instantly splits the payment between up to 3 parties:</p>
            <table class="table table-bordered">
              <thead><tr><th>Party</th><th>Example (R$ 35.50)</th></tr></thead>
              <tbody>
                <tr><td>Driver (75%)</td><td>R$ 26.63</td></tr>
                <tr><td>Franchise (10%)</td><td>R$ 3.55</td></tr>
                <tr><td>Master/Platform (15%)</td><td>R$ 5.33</td></tr>
              </tbody>
            </table>
            <ul>
              <li>Splits are configured per-franchise in Franchise Management</li>
              <li>Each party must have a Pagar.me recipient ID registered</li>
              <li>Split logs stored in <code>pagarme_split_logs</code> table</li>
              <li>Supports full refund via <code>refundPayment</code> action</li>
            </ul>
            <h5>Available Actions:</h5>
            <code>processRidePayment | createRecipient | getSplitDetail | refundPayment | getRecipientBalance</code>
          </div>
        </div>

        <?php if ($result): ?>
        <div class="box box-success">
          <div class="box-header with-border"><h3 class="box-title">API Response</h3></div>
          <div class="box-body"><pre><?= htmlspecialchars(json_encode($result, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)) ?></pre></div>
        </div>
        <?php endif; ?>
      </div>
    </div>

  </section>
</div>
<?php include('../../footer.php'); ?>
